### PR TITLE
Fix insert() to not modify input slice

### LINKED ISSUE #101: Metric emission methods in metrics.go modify input key slice
All the metric emission methods in `Metrics` from metrics.go are checking for the state of certain configuration flags like `EnableHostname`, and if set to true, are modifying the source `key` slice passed as an argument.

See [here](https://github.com/armon/go-metrics/blob/13f9d8e9b41c66738153b7582f1f62add8e407c8/metrics.go#L23) for one such example.

Modification of the input `key` slice causes it to be unusable when emitting it to multiple `Metrics` objects if any configuration flags which cause modification of the input `key` slice are enabled. If different metrics sinks need different configuration, it requires using multiple `Metrics` objects since the config is per-`Metrics` object.

This results in the client being responsible for creating copies of the same `key` slice for each time it emits the metric to different `Metrics` objects, which requires allocating a new `[]string`. This drastically hurts the performance of emitting metrics.

### PR DESCRIPTION
**Pull request by rturner3**
insert() in metrics.go is currently modifying the input slice.
Since this method is only ever used to prepend a value to the beginning of a slice,
changing the implementation to a new method insertAtBeginning() that does not modify
the input slice.

Signed-off-by: Ryan Turner <turner@uber.com>

Closes #101

### CODE REVIEW

**Comment by amoore877** [comment]
This is also more performant, reducing the number of operations in altering the slice

**Comment by rturner3** [comment]
@armon @jefferai It looks like there aren't any default reviewers for this project. I'd appreciate a review when you get a chance!

File: metrics.go [hunk 1]
```diff
@@ -269,10 +269,9 @@ func (m *Metrics) emitRuntimeStats() {
...
-	s = append(s, "")
-	copy(s[i+1:], s[i:])
-	s[i] = v
-	return s
+// Creates a new slice with the provided string value as the first element
+// and the provided slice values as the remaining values.
+// Ordering of the values in the provided input slice is kept in tact in the output slice.
+func insertAtBeginning(v string, s []string) []string {
+	return append([]string{v}, s...)
 }
```
Comment (zmt) [inline metrics.go]: why not just leave it as a flexible insert, but correct the behavior:
```lang=go
func(i int, v string, s []string) []string {
	return append(s[:i], append([]string{v}, s[i:]...)...)
}

See https://github.com/golang/go/wiki/SliceTricks

Comment (amoore877) [reply metrics.go]: the thing is the flexible capability is not used; this is only called with index 0, and seems to have been as such for several years.
Unless there is a clear use case for the flexible version, we should keep it as simple as possible both for easier maintenance and for the slightly better performance (which is impactful for something like a metrics library)

@armon , was there a future use case for having the flexible version for any index?

if I'm reading this correctly, it is potentially insightful to note from @zmt's link that the current implementation is listed as a means to *avoid* creation of an additional slice when inserting at an arbitrary index, though neglects to mention the problem caused by that (the issue this PR fixes)

**Comment by amoore877** [comment]
@armon @jefferai any chance of a review before new year?

**Comment by jefferai** [comment]
I think @zmt is correct, since we don't know whether there was a reason for this in the future, it seems like a better option to simply correct the behavior in a small diff than change it everywhere.

> if I'm reading this correctly, it is potentially insightful to note from @zmt's link that the current implementation is listed as a means to avoid creation of an additional slice when inserting at an arbitrary index, though neglects to mention the problem caused by that

I don't really follow this statement -- in both your updated code and the code suggested by @zmt you're creating a new slice. It's just avoiding the explicit copy.

**Comment by jefferai** [comment]
So I'm a bit confused here. The previous code had one copy of the elements, unless it had to allocate a new slice, in which case it would have two copies. The new code always has two copies of the elements. I'm not seeing how this is easier or more performant.

From the original description of this you're trying to change the code to not modify the underlying input slice. But since there's no insight into the capacity of a slice you can't ever be sure whether or not you're modifying it.

Wouldn't a better solution be to:
1) Explicitly make a new slice with capacity of the existing slice + 1
2) Copy all values up to i into the new slice
3) Insert the new value at i
4) Copy the remaining values into the new slice

This would have just a single copy operation for each element.

**Comment by rturner3** [comment]
> So I'm a bit confused here. The previous code had one copy of the elements, unless it had to allocate a new slice, in which case it would have two copies. The new code always has two copies of the elements. I'm not seeing how this is easier or more performant.
> 
> From the original description of this you're trying to change the code to not modify the underlying input slice. But since there's no insight into the capacity of a slice you can't ever be sure whether or not you're modifying it.
> 
> Wouldn't a better solution be to:
> 
> 1. Explicitly make a new slice with capacity of the existing slice + 1
> 2. Copy all values up to i into the new slice
> 3. Insert the new value at i
> 4. Copy the remaining values into the new slice
> 
> This would have just a single copy operation for each element.

Sounds reasonable. I think I agree, what you've proposed seems like a more readable solution, and guaranteed to be the most performant.
